### ISSUE TITLE
Create a project overview readme

### ISSUE THREAD

**Issue by calebkrauter** [calebkrauter/ryloth#1]
The goal here is to create a [README](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) (name it something like: PROJECT.md) that will help readers to understand the background and goals of this project. It will keep you and other developers oriented as you work on this project.

## Acceptance criteria
- PROJECT.md exists in the root of this repository and contains the following sections,
   - **Background**
   Should answer these questions,
      - How did you decide to start this project?
      - Why do you want to deliver this project?
      - Any other interesting context for this project?
      - Why have you named it the way you did?
   - **Goal**
   Should answer these questions,
      - What is the main goal of this project? (Be specific)
      - What are some key milestones or takeaways that you wish to accomplish?
      - In a perfect world, what would happen with this project?
   - **Requirements**
   Discuss some key requirements or limitations (sort of like, specific goals)
   - **Resources**
   Add links to documents, websites, and resources (include project inspiration).
   - **Reviewers**
   Keep a running list of folks that have reviewed or contributed to the vision of this project.
- [GitHub Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) is used for styling.

**Comment by calebkrauter** [comment]
@coltenkrauter do you have any suggestions on how to write this?

**Comment by coltenkrauter** [comment]
Ya, for sure. Have you written a readme before?

**Comment by calebkrauter** [comment]
I have but it has been a while. I don't know what the best practices and standards are.

**Comment by coltenkrauter** [comment]
I suggest that you read through this to get oriented: [How to write a good README](https://bulldogjob.com/readme/how-to-write-a-good-readme-for-your-github-project)

I'll go ahead and update the issue description with clear goals (known as acceptance criteria).

**Comment by calebkrauter** [comment]
Ok, thank you! I will do that.

**Comment by calebkrauter** [comment]
I just updated the readme. I intend to take some more time to polish it. Feel free to take a look and let me know your feedback if you have any. [README](https://github.com/calebkrauter/ryloth/blob/main/README.md)

**Comment by coltenkrauter** [comment]
Great, I will take a look.

I suggest that you rename it to the file in my suggested above in the description.

**Comment by coltenkrauter** [comment]
Also, rather than committing directly to the `main` branch, please commit to a different branch, and then open up a pull request to `main` so that I can review your changes and leave comments.

**Comment by calebkrauter** [comment]
Ok I will do that. Thank you.

**Comment by calebkrauter** [comment]
I renamed as you suggested and created a pull request. I'll do that moving forward so you can review my work.

**Comment by coltenkrauter** [comment]
I pushed #3 to improve things a bit.
